.TH LIBWXMOTIF-TOOLS 1 "November 22, 2019"
.SH NAME
dialoged_motif \- wxWindows Dialog Editor Version 1.7
.SH SYNOPSIS
.B dialoged_motif
.SH DESCRIPTION
Please see the
.UR file:///usr/share/doc/wx-doc/html/dialoged/dlged.htm
manual
.UE
of the
.B wx-doc
package.
.SH SEE ALSO
.BR tex2rtf (1).
.BR tex2rtf_motif (1),
.BR wxbuild_motif (1),
.BR wxhelp_motif (1),
.BR xpmshow_motif (1),
