.TH LIBWXMOTIF-TOOLS 1 "November 22, 2019"
.SH NAME
tex2rtf \- A LaTeX to RTF and HTML converter
.SH SYNOPSIS
.B tex2rtf [input] [output] [switches]
.SH DESCRIPTION
Please see the
.UR file:///usr/share/doc/wx-doc/html/tex2rtf/t2rtf.htm
manual
.UE
of the
.B wx-doc
package.
.SH SWITCHES
.TP
.B \-interactive
.TP
.B \-bufsize \fIsize_in_K\fP
.TP
.B \-charset \fIpc\fP | \fIpca\fP | \fIansi\fP | \fImac\fP (default ansi)
.TP
.B \-twice
.TP
.B \-sync
.TP
.B \-macros \fIfilename\fP
.TP
.B \-winhelp
.TP
.B \-rtf
.TP
.B \-html
.TP
.B \-xlp
.SH SEE ALSO
.BR dialoged_motif (1).
.BR tex2rtf_motif (1),
.BR wxbuild_motif (1),
.BR wxhelp_motif (1),
.BR xpmshow_motif (1),
