.TH LIBWXMOTIF-TOOLS 1 "November 22, 2019"
.SH NAME
wxbuild_motif \- wxBuilder 2.0
.SH SYNOPSIS
.B wxbuild_motif
.SH DESCRIPTION
Please see the
.UR file:///usr/share/doc/wx-doc/html/wxbuild/build.htm
manual
.UE
of the
.B wx-doc
package.
.SH SEE ALSO
.BR dialoged_motif (1).
.BR tex2rtf (1),
.BR tex2rtf_motif (1),
.BR wxhelp_motif (1),
.BR xpmshow_motif (1),
