.TH LIBWXMOTIF-TOOLS 1 "November 22, 2019"
.SH NAME
xpmshow_motif \- Showing and converting between XPM and BMP files
.SH SYNOPSIS
.B xpmshow_motif
.SH DESCRIPTION
Please see the
.UR file:///usr/share/doc/wx-doc/html/wx/wx12.htm#topic7
manual
.UE
of the
.B wx-doc
package.
.SH SEE ALSO
.BR dialoged_motif (1).
.BR tex2rtf (1),
.BR tex2rtf_motif (1),
.BR wxbuild_motif (1),
.BR wxhelp_motif (1),
